### ISSUE TITLE
No users module?

### ISSUE THREAD

**Issue by mg1075** [chrisedg87/BeanJS#1]
Did you try to implement the users module from MEAN.JS?

https://github.com/meanjs/mean/tree/master/modules

I think converting that "users" module is the crux of switching away from Mongoose but retaining as much as you can of the MEAN.JS infrastructure.

**Comment by chrisedg87** [comment]
This is definitely on my to do list. Will try and get it added in the next week if possible.

**Comment by chrisedg87** [comment]
Finally got some time to do this. Have added the basic user module but needs a little work to get the social network accounts working.

**Comment by mg1075** [comment]
Recently found another SQL-friendly implementation of MEAN.JS, with this one based on sequelize: 
https://github.com/StetSolutions/pean
